language: ruby
rvm:
  - 2.7.0
env:
  - DB=pgsql
services:
  - postgresql
addons:
  code_climate:
      repo_token: fb43fe870fb2a6d1517b0f6ffc783d023ee258395112255982bfd5672bc47f83
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rails db:migrate
  - bundle exec rspec
after_success:
  - bundle exec codeclimate-test-reporter
